version: '3.8'

services:
  user-service:
    image: arumandesu/user-service
    container_name: "user-service"
    ports:
      - "44044:44044"
    networks:
      - new
    depends_on:
      - postgres
      - redis

  api-gateway:
    image: arumandesu/api-gateway
    container_name: "api-gateway"
    ports:
      - "5000:5000"
    networks:
      - new

  postgres:
    image: postgres:16
    container_name: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      new:
        aliases:
          - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb

  redis:
    image: redis/redis-stack:latest
    container_name: "redis"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - new



networks:
    new:

volumes:
  postgres-data:
  redis-data:
